# Generated by Django 5.0.4 on 2024-04-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_age_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('name_first', models.CharField(max_length=100)),
                ('name_last', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
