# Generated by Django 5.0.4 on 2024-04-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_worker_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='location',
        ),
        migrations.AddField(
            model_name='worker',
            name='work',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.work'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
